import { createWorkItem } from "./azureDevops";
import { saveDecisionRecords } from "./decisionStore";
import { 
  runSignalAgent, 
  runHistorianAgent, 
  runAuditorAgent, 
  runChallengerAgent, 
  runSynthesizerAgent 
} from "../agents";
import { FailureSimulation } from "@foresight/shared";
import { startAgent, completeAgent } from "../teams/activityStore";
import { saveSimulation } from "../teams/simulationStore";

export async function runSimulationWorkflow(prompt: string, decisionId: string) {
  startAgent(decisionId, "SIGNAL");
  const signal = await runSignalAgent(prompt);
  completeAgent(decisionId, "SIGNAL");

  startAgent(decisionId, "HISTORIAN");
  const historian = await runHistorianAgent(signal.data, prompt);
  completeAgent(decisionId, "HISTORIAN");

  startAgent(decisionId, "AUDITOR");
  const auditor = await runAuditorAgent();
  completeAgent(decisionId, "AUDITOR");

  startAgent(decisionId, "CHALLENGER");
  const challenger = await runChallengerAgent(signal.data, historian.data);
  completeAgent(decisionId, "CHALLENGER");

  startAgent(decisionId, "SYNTHESIZER");
  const synthesizer = await runSynthesizerAgent(signal.data, historian.data, auditor.data, challenger.data);
  completeAgent(decisionId, "SYNTHESIZER");

  const simulation: FailureSimulation = {
    context: signal.data,
    retrievedDocuments: historian.data,
    constraints: auditor.data,
    assumptions: challenger.data,
    scenarios: synthesizer.data,
    agentTraces: {
      SIGNAL: signal.reasoningTrace,
      HISTORIAN: historian.reasoningTrace,
      AUDITOR: auditor.reasoningTrace,
      CHALLENGER: challenger.reasoningTrace,
      SYNTHESIZER: synthesizer.reasoningTrace
    }
  };

  const createdWorkItems: { id: number; title: string; url?: string }[] = [];
  for (const scenario of simulation.scenarios || []) {
    try {
      const workItem = await createWorkItem(
        scenario.title,
        scenario.impact || "Generated by Foresight"
      );
      createdWorkItems.push({
        id: workItem.id,
        title: scenario.title,
        url: workItem._links?.html?.href
      });
    } catch (err) {
      console.error("Azure Work Item Creation Failed:", err);
    }
  }

  const decisionRecords = simulation.scenarios.map((scenario) => {
    const matchingItem = createdWorkItems.find(wi => wi.title === scenario.title);
    return {
      scenarioId: scenario.id,
      generatedBy: [
        "Historian",
        "Auditor",
        "Challenger",
        "Synthesizer"
      ],
      evidence: simulation.retrievedDocuments.map(
        (doc) => doc.title
      ),
      constraints: simulation.constraints.map(
        (c) => c.description
      ),
      assumptions: simulation.assumptions.map(
        (a) => a.assumption
      ),
      confidence: simulation.context.confidence,
      timestamp: new Date().toISOString(),
      ...(matchingItem && {
        azureWorkItemId: matchingItem.id,
        azureWorkItemTitle: matchingItem.title,
        azureWorkItemUrl: matchingItem.url || `https://dev.azure.com/foresight-buildai/FORESIGHT/_workitems/edit/${matchingItem.id}`
      })
    };
  });

  saveDecisionRecords(decisionRecords);

  const finalResult = {
    ...simulation,
    decisionRecords,
    azureWorkItems: createdWorkItems
  };

  saveSimulation(decisionId, finalResult);

  return finalResult;
}
